.TH SPINDOCGENERATOR "1" "October 2012" "spindocgenerator 0.4" "User Commands"
.SH NAME
spindocgenerator \- OSC protocol documentation generator for the SPIN Framework
.SH SYNOPSIS
spindocgenerator
.SH DESCRIPTION
spindocgenerator generates the OSC protocol documentation for the SPIN Framework as a single html file named
.I oscprotocol.html
by default.
.SH OPTIONS
spindocgenerator does not take any option.
.SH "REPORTING BUGS"
https://sourceforge.net/apps/trac/spinframework/
.SH "SEE ALSO"
spinviewer (1), spinserver (1)
