TOPDIR = ../../..
include $(TOPDIR)/Make/makedefs 

CXXFILES =\$(_REPEAT_FILE_)
	$(_FILE_NAME_)\$(_END_REPEAT_)

LIBS   += -l$(_WRAPPER_NAME_) -losg -losgIntrospection $(_DEPENDENCIES_) $(GL_LIBS) $(OTHER_LIBS)

OPTF = -O

TARGET_BASENAME = $(_WRAPPER_NAME_)
include $(TOPDIR)/Make/cygwin_wrapper_def
WRAPPER = $(WRAPPER_PREFIX)$(TARGET_BASENAME).$(PLUGIN_EXT)

include $(TOPDIR)/Make/makerules 
