// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <cppintrospection/ReflectionMacros>
#include <cppintrospection/TypedMethodInfo>
#include <cppintrospection/StaticMethodInfo>
#include <cppintrospection/Attributes>

#include <DraggerTrackball.h>
#include <DraggerWith3Axes.h>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_OBJECT_REFLECTOR(osgManipulator::DraggerWith3Axes)
	I_DeclaringFile("DraggerWith3Axes.h");
	I_Constructor0(____DraggerWith3Axes,
	               "",
	               "");
	I_Method2(, META_OSGMANIPULATOR_Object, IN, osgManipulator, x, IN, osgManipulator::DraggerWith3Axes, x,
	          Properties::NON_VIRTUAL,
	          ____META_OSGMANIPULATOR_Object__osgManipulator__DraggerWith3Axes,
	          "",
	          "Setup default geometry for dragger. ");
END_REFLECTOR

