// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <cppintrospection/ReflectionMacros>
#include <cppintrospection/TypedMethodInfo>
#include <cppintrospection/StaticMethodInfo>
#include <cppintrospection/Attributes>

#include <ImageTexture.h>
#include <SceneManager.h>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_ENUM_REFLECTOR(spin::ImageTexture::TextureMode)
	I_DeclaringFile("ImageTexture.h");
	I_EnumLabel(spin::ImageTexture::TEXTURE_2D);
	I_EnumLabel(spin::ImageTexture::TEXTURE_RECTANGLE);
END_REFLECTOR

BEGIN_OBJECT_REFLECTOR(spin::ImageTexture)
	I_DeclaringFile("ImageTexture.h");
	I_BaseType(spin::Shader);
	I_Constructor2(IN, spin::SceneManager *, sceneManager, IN, const char *, initID,
	               ____ImageTexture__SceneManager_P1__C5_char_P1,
	               "",
	               "");
	I_Method0(void, debug,
	          Properties::VIRTUAL,
	          __void__debug,
	          "",
	          "Print debug information to console. ");
	I_Method0(bool, isValid,
	          Properties::NON_VIRTUAL,
	          __bool__isValid,
	          "",
	          "Returns whether there is a currently valid image texture ");
	I_Method1(void, setPath, IN, const char *, newPath,
	          Properties::NON_VIRTUAL,
	          __void__setPath__C5_char_P1,
	          "",
	          "Creates a texture from a path on disk. ");
	I_Method0(const char *, getPath,
	          Properties::NON_VIRTUAL,
	          __C5_char_P1__getPath,
	          "",
	          "");
	I_Method1(void, setTextureMode, IN, spin::ImageTexture::TextureMode, mode,
	          Properties::NON_VIRTUAL,
	          __void__setTextureMode__TextureMode,
	          "",
	          "");
	I_Method0(int, getTextureMode,
	          Properties::NON_VIRTUAL,
	          __int__getTextureMode,
	          "",
	          "");
	I_Method1(void, setTextureResize, IN, bool, b,
	          Properties::NON_VIRTUAL,
	          __void__setTextureResize__bool,
	          "",
	          "");
	I_Method0(int, getTextureResize,
	          Properties::NON_VIRTUAL,
	          __int__getTextureResize,
	          "",
	          "");
	I_Method0(std::vector< lo_message >, getState,
	          Properties::VIRTUAL,
	          __std_vectorT1_lo_message___getState,
	          "",
	          "Just like a ReferencedNode, each subclass of ReferencedStateSet must override the getState() method to pass it's current state. ");
	I_ProtectedMethod0(void, draw,
	                   Properties::NON_VIRTUAL,
	                   Properties::NON_CONST,
	                   __void__draw,
	                   "",
	                   "");
	I_SimpleProperty(const char *, Path, 
	                 __C5_char_P1__getPath, 
	                 __void__setPath__C5_char_P1);
	I_SimpleProperty(std::vector< lo_message >, State, 
	                 __std_vectorT1_lo_message___getState, 
	                 0);
	I_SimpleProperty(int, TextureMode, 
	                 __int__getTextureMode, 
	                 0);
	I_SimpleProperty(bool, TextureResize, 
	                 0, 
	                 __void__setTextureResize__bool);
END_REFLECTOR

