// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <cppintrospection/ReflectionMacros>
#include <cppintrospection/TypedMethodInfo>
#include <cppintrospection/StaticMethodInfo>
#include <cppintrospection/Attributes>

#include <spinServerContext.h>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_OBJECT_REFLECTOR(spin::spinServerContext)
	I_DeclaringFile("spinServerContext.h");
	I_BaseType(spin::spinBaseContext);
	I_Constructor0(____spinServerContext,
	               "",
	               "");
	I_Method0(bool, start,
	          Properties::VIRTUAL,
	          __bool__start,
	          "",
	          "");
	I_Method0(void, refreshSubscribers,
	          Properties::NON_VIRTUAL,
	          __void__refreshSubscribers,
	          "",
	          "");
	I_Method0(void, startSyncThread,
	          Properties::NON_VIRTUAL,
	          __void__startSyncThread,
	          "",
	          "Starts the thread that sends synchronization timecode (syncThread) ");
END_REFLECTOR

