// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <cppintrospection/ReflectionMacros>
#include <cppintrospection/TypedMethodInfo>
#include <cppintrospection/StaticMethodInfo>
#include <cppintrospection/Attributes>

#include <spinlog.h>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_VALUE_REFLECTOR(spin::logbuf)
	I_DeclaringFile("spinlog.h");
	I_Constructor1(IN, const char *, logpath,
	               Properties::NON_EXPLICIT,
	               ____logbuf__C5_char_P1,
	               "",
	               "");
	I_Method1(void, set_priority, IN, spin::LogPriority, p,
	          Properties::NON_VIRTUAL,
	          __void__set_priority__LogPriority,
	          "",
	          "");
	I_Constructor1(IN, const char *, logpath,
	               Properties::NON_EXPLICIT,
	               ____logbuf__C5_char_P1,
	               "",
	               "");
	I_Method1(void, set_priority, IN, spin::LogPriority, p,
	          Properties::NON_VIRTUAL,
	          __void__set_priority__LogPriority,
	          "",
	          "");
	I_PublicMemberProperty(bool, bCOUT);
	I_PublicMemberProperty(bool, bFILE);
	I_PublicMemberProperty(bool, bWXLG);
END_REFLECTOR

BEGIN_VALUE_REFLECTOR(spin::spinLog)
	I_DeclaringFile("spinlog.h");
	I_Constructor1(IN, const char *, logpath,
	               Properties::NON_EXPLICIT,
	               ____spinLog__C5_char_P1,
	               "",
	               "");
	I_Method1(void, set_priority, IN, spin::LogPriority, pr,
	          Properties::NON_VIRTUAL,
	          __void__set_priority__LogPriority,
	          "",
	          "Sets priority ");
	I_Method1(void, enable_cout, IN, bool, b,
	          Properties::NON_VIRTUAL,
	          __void__enable_cout__bool,
	          "",
	          "");
	I_Method1(void, enable_logfile, IN, bool, b,
	          Properties::NON_VIRTUAL,
	          __void__enable_logfile__bool,
	          "",
	          "");
	I_Constructor1(IN, const char *, logpath,
	               Properties::NON_EXPLICIT,
	               ____spinLog__C5_char_P1,
	               "",
	               "");
	I_Method1(void, set_priority, IN, spin::LogPriority, pr,
	          Properties::NON_VIRTUAL,
	          __void__set_priority__LogPriority,
	          "",
	          "");
	I_Method1(void, enable_cout, IN, bool, b,
	          Properties::NON_VIRTUAL,
	          __void__enable_cout__bool,
	          "",
	          "");
	I_Method1(void, enable_logfile, IN, bool, b,
	          Properties::NON_VIRTUAL,
	          __void__enable_logfile__bool,
	          "",
	          "");
	I_Method1(void, enable_wxlog, IN, bool, b,
	          Properties::NON_VIRTUAL,
	          __void__enable_wxlog__bool,
	          "",
	          "");
END_REFLECTOR

BEGIN_ENUM_REFLECTOR(spin::LogPriority)
	I_DeclaringFile("spinlog.h");
	I_EnumLabel(spin::INFO);
	I_EnumLabel(spin::DEV);
	I_EnumLabel(spin::ERROR);
	I_EnumLabel(spin::INFO);
	I_EnumLabel(spin::DEV);
	I_EnumLabel(spin::ERROR);
END_REFLECTOR

