// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <cppintrospection/ReflectionMacros>
#include <cppintrospection/TypedMethodInfo>
#include <cppintrospection/StaticMethodInfo>
#include <cppintrospection/Attributes>

#include <spinlogwx.h>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_ENUM_REFLECTOR(spin::LogPriority)
	I_DeclaringFile("spinlogwx.h");
	I_EnumLabel(spin::INFO);
	I_EnumLabel(spin::DEV);
	I_EnumLabel(spin::ERROR);
	I_EnumLabel(spin::INFO);
	I_EnumLabel(spin::DEV);
	I_EnumLabel(spin::ERROR);
END_REFLECTOR

