// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/StaticMethodInfo>
#include <osgIntrospection/Attributes>

#include <spinUtil.h>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_VALUE_REFLECTOR(_symbol)
	I_DeclaringFile("spinUtil.h");
	I_Constructor0(_____symbol,
	               "",
	               "");
	I_PublicMemberProperty(char *, s_name);
	I_PublicMemberProperty(osg::Object *, s_thing);
	I_PublicMemberProperty(struct _symbol *, s_next);
	I_PublicMemberProperty(ReferencedType, s_type);
END_REFLECTOR

