// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <cppintrospection/ReflectionMacros>
#include <cppintrospection/TypedMethodInfo>
#include <cppintrospection/StaticMethodInfo>
#include <cppintrospection/Attributes>

#include <ViewerManipulator.h>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_VALUE_REFLECTOR(spin::ViewerManipulator)
	I_DeclaringFile("ViewerManipulator.h");
	I_Constructor0(____ViewerManipulator,
	               "",
	               "");
	I_Method1(void, setPicker, IN, bool, b,
	          Properties::NON_VIRTUAL,
	          __void__setPicker__bool,
	          "",
	          "Enables or disables use of the mouse to pick nodes. ");
	I_Method1(void, setMover, IN, bool, b,
	          Properties::NON_VIRTUAL,
	          __void__setMover__bool,
	          "",
	          "Enables or disables the use of camera motion controls. ");
	I_Method1(void, setRaw, IN, bool, b,
	          Properties::NON_VIRTUAL,
	          __void__setRaw__bool,
	          "",
	          "Enables or disables raw mouse events. TO_BE_VERIFIED ");
	I_Method2(bool, handle, IN, const osgGA::GUIEventAdapter &, ea, IN, osgGA::GUIActionAdapter &, aa,
	          Properties::NON_VIRTUAL,
	          __bool__handle__C5_osgGA_GUIEventAdapter_R1__osgGA_GUIActionAdapter_R1,
	          "",
	          "if the userNode's nodepath has changed, we must call setTrackNode again to force NodeTrackerManipulator to store the proper nodePath ");
	I_Method1(void, handleKeypress, IN, const osgGA::GUIEventAdapter &, ea,
	          Properties::NON_VIRTUAL,
	          __void__handleKeypress__C5_osgGA_GUIEventAdapter_R1,
	          "",
	          "Handles keyboard input. ");
	I_Method2(void, handleMouse, IN, osgViewer::View *, view, IN, const osgGA::GUIEventAdapter &, ea,
	          Properties::NON_VIRTUAL,
	          __void__handleMouse__osgViewer_View_P1__C5_osgGA_GUIEventAdapter_R1,
	          "",
	          "Handles mouse interaction with the scene. Includes camera navigation, picking interactive nodes and manipulating nodes with manipulator handles. ");
	I_SimpleProperty(bool, Mover, 
	                 0, 
	                 __void__setMover__bool);
	I_SimpleProperty(bool, Picker, 
	                 0, 
	                 __void__setPicker__bool);
	I_SimpleProperty(bool, Raw, 
	                 0, 
	                 __void__setRaw__bool);
END_REFLECTOR

